name: Lowest Number Test
on: [push]
jobs:
   lowest_number_test:
     name: Lowest Number Test
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
     - name: Set up Python 3.10
       uses: actions/setup-python@v3
       with:
         python-version: "3.10"
     - name: Produce Test 1 Output
       run: python find_lowest_number.py test1_input.txt test1_result.txt
     - name: Compare Test 1 expected output to actual
       run: diff test1_expected.txt test1_result.txt
     
     - name: Produce Test 2 Output
       run: python find_lowest_number.py test2_input.txt test2_result.txt
     - name: Compare Test 2 expected output to actual
       run: diff test2_expected.txt test2_result.txt

     - name: Produce Test 3 Output
       run: python find_lowest_number.py test3_input.txt test3_result.txt
     - name: Compare Test 3 expected output to actual
       run: diff test3_expected.txt test3_result.txt
