name: Lowest Number Test
on: [push]
jobs:
   lowest_number_test:
     name: Lowest Number Test
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
     - name: Set up Python 3.10
       uses: actions/setup-python@v3
       with:
         python-version: "3.10"
     - name: Produce Test 1 Output
       run: python3 find_lowest_number.py test_data/test1_input.txt test_data/test1_output.txt
     - name: Compare Test 1 Expected Output to Actual Output
       run: diff test_data/test1_expected.txt test_data/test1_output.txt
     - name: Produce Test 2 Output
       run: python3 find_lowest_number.py test_data/test2_input.txt test_data/test2_output.txt
     - name: Compare Test 2 Expected Output to Actual Output
       run: diff test_data/test2_expected.txt test_data/test2_output.txt
     - name: Produce Test 3 Output
       run: python3 find_lowest_number.py test_data/test3_input.txt test_data/test3_output.txt
     - name: Compare Test 3 Expected Output to Actual Output
       run: diff test_data/test3_expected.txt test_data/test3_output.txt
